const LOAD_EXPENSES = 'LOAD_EXPENSES'
const LOAD_EXPENSES_ERROR = 'LOAD_EXPENSES_ERROR'
const CREATE_EXPENSE = 'CREATE_EXPENSE'
const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR'
const UPDATE_EXPENSE = 'UPDATE_EXPENSE'
const UPDATE_EXPENSE_ERROR = 'UPDATE_EXPENSE_ERROR'
const DELETE_EXPENSE = 'DELETE_EXPENSE'
const DELETE_EXPENSE_ERROR = 'DELETE_EXPENSE_ERROR'
const LOAD_INCOMES = 'LOAD_INCOMES'
const LOAD_INCOMES_ERROR = 'LOAD_INCOMES_ERROR'
const CREATE_INCOME = 'CREATE_INCOME'
const CREATE_INCOME_ERROR = 'CREATE_INCOME_ERROR'
const UPDATE_INCOME = 'UPDATE_INCOME'
const UPDATE_INCOME_ERROR = 'UPDATE_INCOME_ERROR'
const DELETE_INCOME = 'DELETE_INCOME'
const DELETE_INCOME_ERROR = 'DELETE_INCOME_ERROR'
const SET_USER = 'SET_USER'
const DELETE_USER = 'DELETE_USER'

export {
	LOAD_EXPENSES,
	LOAD_EXPENSES_ERROR,
	CREATE_EXPENSE,
	CREATE_EXPENSE_ERROR,
	UPDATE_EXPENSE,
	UPDATE_EXPENSE_ERROR,
	DELETE_EXPENSE,
	DELETE_EXPENSE_ERROR,
	LOAD_INCOMES,
	LOAD_INCOMES_ERROR,
	CREATE_INCOME,
	CREATE_INCOME_ERROR,
	UPDATE_INCOME,
	UPDATE_INCOME_ERROR,
	DELETE_INCOME,
	DELETE_INCOME_ERROR,
	SET_USER,
	DELETE_USER
}