const CREATE_EXPENSE = 'CREATE_EXPENSE'
const UPDATE_EXPENSE = 'UPDATE_EXPENSE'
const DELETE_EXPENSE = 'DELETE_EXPENSE'
const CREATE_INCOME = 'CREATE_INCOME'
const UPDATE_INCOME = 'UPDATE_INCOME'
const DELETE_INCOME = 'DELETE_INCOME'
const SIGN_IN_USER = 'SIGN_IN_USER'
const SIGN_OUT_USER = 'SIGN_OUT_USER'

export {
	CREATE_EXPENSE,
	UPDATE_EXPENSE,
	DELETE_EXPENSE,
	CREATE_INCOME,
	UPDATE_INCOME,
	DELETE_INCOME,
	SIGN_IN_USER,
	SIGN_OUT_USER
}